######################################################################
# Automatically generated by qmake (3.0) Mon Mar 17 21:43:40 2014
######################################################################

TEMPLATE = app
TARGET = cone
INCLUDEPATH += .

# Input
SOURCES += cone.cpp
